### ISSUE TITLE
Where is data for reading comprehnesion?

### ISSUE THREAD

**Issue by puraminy** [persiannlp/parsinlu#13]
Hi,
Thank you for providing this benchmark,

However, I can't find data for reading comprehension in the data folder.

**Comment by danyaljj** [comment]
We have an evaluation set here: https://github.com/persiannlp/parsinlu/tree/master/data/reading_comprehension 
It is the only task that does not have train/dev set, yet. We hope to include the train/dev sets in a couple of weeks. 

FYI @maxsonate

**Comment by danyaljj** [comment]
The train/dev data for reading-comprehension is public now: https://github.com/persiannlp/parsinlu/tree/master/data/reading_comprehension
