### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'early_stop_callback'

### ISSUE THREAD

**Issue by puraminy** [persiannlp/parsinlu#15]
I cloned the package and installed requirements.txt

Then I wento the scripts directory and run this command:

`./train_and_evaluate_reading_comprehension_baselines.sh `

But I got the following error:

```
Traceback (most recent call last):
  File "../src/run_seq2seq.py", line 344, in <module>
    main(args)
  File "../src/run_seq2seq.py", line 322, in main
    logger=logger,
  File "/home/pouramini/parsinlu/src/lightning_base.py", line 329, in generic_train
    **train_params,
  File "/home/pouramini/miniconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/env_vars_connector.py", line 41, in overwrite_by_env_vars
    return fn(self, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'early_stop_callback'


```

It might be related to some enviornment setting or version mismatche, if you know the error please guide me.

**Comment by danyaljj** [comment]
Salaam, sorry about that. Currently, we don't have training data for Persian reading-comprehension (as per the response in #13). I will add a comment in the script until we add the training data.

**Comment by puraminy** [comment]
Thank you for your response! I'm interested in knowning your algorithm and your performance on reading comprehension task.  However, I couldn't run the script. 
Do you have any treaining data? because I thought it could be costly to provide such data fro this task, and you probably used transfer learning.  

Anywyas, if you have training data, I would be glad to use it in my method, and would be glad if I can have access to it. So, I'm watching yoru dataset for this data to be provided.

**Comment by puraminy** [comment]
I cloned the updated repository and run the script for reading comprehension and again I got the above error. So, this error persists still.

**Comment by danyaljj** [comment]
The script is updated. All the RC baselines (except mT5) should work with this script now.
