### ISSUE TITLE
empty result

### ISSUE THREAD

**Issue by mmtIr** [persiannlp/parsinlu#29]
I ran train_and_evaluate_entailment_baselines.sh and got results in /scripts/runs/   . All events.out.tfevents files have same 40 bytes size and are quite empty. How can I solve it?

**Comment by danyaljj** [comment]
What is the console output?

**Comment by mmtIr** [comment]
[output1.txt](https://github.com/persiannlp/parsinlu/files/6565710/output1.txt)

**Comment by danyaljj** [comment]
I see "CUDA out of memory" error in your logs. Either reduce the batch size or run your experiments on a bigger GPU.
