### ISSUE TITLE
Looking for best NLI model

### ISSUE THREAD

**Issue by milad-mr** [persiannlp/parsinlu#30]
What is Parsnlu's best model for entailment.

Have you trained 'persiannlp/parsbert-base-parsinlu-entailment' on FarsTail dataset?

**Comment by danyaljj** [comment]
> What is Parsnlu's best model for entailment. 

You can try models here: https://huggingface.co/persiannlp 

> Have you trained 'persiannlp/parsbert-base-parsinlu-entailment' on FarsTail dataset? 

I believe so.
