### ISSUE TITLE
Example for wikibert-base-parsinlu-multiple-choice seemed not working.

### ISSUE THREAD

**Issue by ghost** [persiannlp/parsinlu#31]
I tried [this example for wikibert-base-parsinlu-multiple-choice](https://huggingface.co/persiannlp/wikibert-base-parsinlu-multiple-choice).

I got these outputs:

```
MultipleChoiceModelOutput(loss=None, logits=tensor([[2.1362],
        [2.1362],
        [2.1362],
        [2.1362]], grad_fn=<ViewBackward>), hidden_states=None, attentions=None)
MultipleChoiceModelOutput(loss=None, logits=tensor([[2.1362],
        [2.1362],
        [2.1362],
        [2.1362]], grad_fn=<ViewBackward>), hidden_states=None, attentions=None)
MultipleChoiceModelOutput(loss=None, logits=tensor([[2.1362],
        [2.1362],
        [2.1362],
        [2.1362]], grad_fn=<ViewBackward>), hidden_states=None, attentions=None)
```

But how do I obtain which candidate was guessed? Those outputs did not make a sense.

The ones that involves BERT had same examples except model name so I guess they would output something similar. Only [MT5 ones](https://huggingface.co/persiannlp/mt5-base-parsinlu-multiple-choice) seemed to output what I expected.

**Comment by danyaljj** [comment]
I am not sure. Have you tried using an older HF version? 
https://github.com/persiannlp/parsinlu/blob/master/requirements.txt#L1

**Comment by ghost** [comment]
First of all I was running the examples on my Google Colab.

# How first post can be reproduced
I ran this first:

```
!git clone https://github.com/persiannlp/parsinlu.git
%cd parsinlu
%cat requirements.txt | sed '/transformers/s/==.*//' | xargs pip install
```

`transformers==4.11.3` was installed.

And then I copied and pasted two example codes.

The example of MT5 worked well while wikibert's one was unexpected.

# Trying your suggestion
I replaced the header with this:

```
!git clone https://github.com/persiannlp/parsinlu.git
%cd parsinlu
%cat requirements.txt | xargs pip install
```

Now `transformers==3.3.1`.
This made it worse:

MT5:

```python
ImportError: cannot import name 'MT5ForConditionalGeneration' from 'transformers' (/usr/local/lib/python3.7/dist-packages/transformers/__init__.py)
```

wikibert:

```python
OSError: Can't load config for 'persiannlp/wikibert-base-parsinlu-multiple-choice'. Make sure that:

- 'persiannlp/wikibert-base-parsinlu-multiple-choice' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'persiannlp/wikibert-base-parsinlu-multiple-choice' is the correct path to a directory containing a config.json file
```

## Additional attempt for wikibert
Additionally I tried replacing the line that begins with `model_name = ` with this:

```python
model_name = "https://huggingface.co/persiannlp/wikibert-base-parsinlu-multiple-choice"
```

Then I got this on `tokenizer = AutoTokenizer.from_pretrained(model_name)`:

```python
OSError: Couldn't reach server at 'https://huggingface.co/persiannlp/wikibert-base-parsinlu-multiple-choice' to download configuration file or configuration file is not a valid JSON file. Please check network or file content here: /root/.cache/torch/transformers/c835408c015190d62934aec51a31f3c89d80f85b6cc769589fba323a600ffbe8.096cd4c0dc659a0d7e7c61a40dae5d5e6a606ea26fe3dbcba109ac847e78355a.
```

**Comment by ghost** [comment]
I'm sorry, but I am not interested in this any more.
