### ISSUE TITLE
Fine-tune Huggingface model

### ISSUE THREAD

**Issue by hamid-mp** [persiannlp/parsinlu#33]
Hi, first I want to send gratitude for sharing your great work. I'm new to NLP field and I have to a task to do, so I've looked at your model in `hugging face` and I want to fine-tune your model. So how can I fine-tune your model with python `transformer` package?
Thanks a lot

**Comment by Saba-Heydaridoost** [comment]
Hello, I have the same issue. I would appreciate it if you could explain how to fine-tune the model.
Thanks in advance.

**Comment by danyaljj** [comment]
This repository is mainly about the data. The code provided here is outdated. 
You need to read through the examples in the Huggingface Transformers library to learn about fine-tuning process.
